version: "3"
services: 
    mongodb:
        image: mongo
        container_name: mongo
        ports: 
            - 27017
        hostname: mongo
        volumes: 
            - $HOME/mongodb/data/db:/data/db