version: "3"
services: 
    mongodb:
        image: mongo
        container_name: mongo
        ports: 
            - 27017:27017
        hostname: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes: 
            - $HOME/dev/Applications/mongodb/data/db:/data/db
